# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
revisionHistoryLimit: 1
image:
  repository: org-hierarchy
  tag: 1.0.0
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 200m
      memory: 300Mi
  readinessProbe: {}
  livenessProbe:
   httpGet:
     path: /healtz
     port: 8080
   initialDelaySeconds: 40
   periodSeconds: 10
service:
  name: Node
  type: NodePort
  servicePort: 8080
ingressDomain: "Bureaucr.at"
namespace: "k8s-test"

